[package]
name = "core_engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
contracts = { path = "../contracts" }
dump_runtime = { path = "../dump_runtime" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
